import 'package:flutter/material.dart';

import '../../models/calendar_models.dart';
import '../../models/inventory_models.dart';
import '../../models/popup_models.dart';

class MockPopupData {
  const MockPopupData._();

  static final popups = <Popup>[
    const Popup(
      id: 'whipped-seongsu',
      title: '휩드(WHIPPED) 팩클렌저 팝업',
      category: '뷰티',
      area: '성수동',
      address: '서울 성동구 연무장길 14',
      subtitle: '피부에 양보하는 비건 팩클렌저 휩드 성수 하우스 팝업',
      period: '2026.05.01 - 2026.06.30',
      heroLabel: 'NEW',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '11:00 - 21:00',
      distance: '185m away',
      dday: 'D-29',
      tags: ['VEGAN', 'BEAUTY', 'CLEANSER'],
      colors: [Color(0xFF78350F), Color(0xFFFEF3C7)],
      imagePath: 'assets/images/calendar_beauty.png',
      status: PopupStatus.inProgress,
      latitude: 37.5440,
      longitude: 127.0540,
      isOperating: true,
    ),
    const Popup(
      id: 'drg-seongsu',
      title: '닥터지 무빙 팝업',
      category: '뷰티',
      area: '성수동',
      address: '서울 성동구 연무장길 18',
      subtitle: '닥터지 각.보.자 피부 수분 충전 무빙 체험 팝업',
      period: '2026.06.01 - 2026.06.15',
      heroLabel: 'NEW',
      waitTime: '약 12분',
      entryFee: '무료',
      hours: '10:30 - 19:30',
      distance: '500m',
      dday: 'D-14',
      tags: ['BEAUTY', 'DRG', 'MOVING'],
      colors: [Color(0xFF515D62), Color(0xFFB7C6C8)],
      imagePath: 'assets/images/home_hero_popup.jpg',
      status: PopupStatus.inProgress,
      latitude: 37.5430,
      longitude: 127.0553,
      isOperating: true,
    ),
    const Popup(
      id: 'papajohns-toystory',
      title: "파파존스 '토이 스토리 피자 플래닛'",
      category: '음식',
      area: '성수동',
      address: '서울 성동구 뚝섬로1길 63',
      subtitle: '토이 스토리 5 개봉 기념 글로벌 피자 아케이드 콘셉트 팝업',
      period: '2026.06.12 - 2026.06.14',
      heroLabel: 'HOT',
      waitTime: '약 90분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '310m away',
      dday: 'D-11',
      tags: ['PIZZA', 'TOY_STORY', 'DISNEY'],
      colors: [Color(0xFF451A03), Color(0xFFFEF3C7)],
      imagePath: 'assets/images/detail_nearby_restaurant.png',
      status: PopupStatus.openingSoon,
      latitude: 37.5443,
      longitude: 127.0550,
      isOperating: false,
    ),
    const Popup(
      id: 'moncler-puppy',
      title: "몽클레르 '퍼피 서머' 팝업",
      category: '패션',
      area: '성수동',
      address: '서울 성동구 성수동 팝업공간',
      subtitle: '몽클레르의 신규 퍼피 서머 컬렉션 글로벌 팝업',
      period: '2026.05.01 - 2026.05.03',
      heroLabel: 'CLOSED',
      waitTime: '0분',
      entryFee: '무료',
      hours: '10:00 - 20:00',
      distance: '90m away',
      dday: '종료',
      tags: ['MONCLER', 'PUPPY', 'SUMMER'],
      colors: [Color(0xFF065F46), Color(0xFFD1FAE5)],
      imagePath: 'assets/images/detail_nearby_cafe.png',
      status: PopupStatus.ended,
      latitude: 37.5443,
      longitude: 127.0550,
      isOperating: false,
    ),
    const Popup(
      id: 'pokemon-oliveyoung',
      title: '포켓몬 30주년 파티 팝업',
      category: '캐릭터',
      area: '성수동',
      address: '서울 성동구 성수이로 90',
      subtitle: '올리브영 성수 N에서 열리는 포켓몬 30주년 한정 굿즈 팝업',
      period: '2026.05.01 - 2026.06.21',
      heroLabel: 'HOT',
      waitTime: '약 15분',
      entryFee: '무료',
      hours: '12:00 - 20:00',
      distance: '70m away',
      dday: 'D-20',
      tags: ['POKEMON', 'CHARACTER', 'GOODS'],
      colors: [Color(0xFF1E3F20), Color(0xFFE8F5E9)],
      imagePath: 'assets/images/calendar_gallery.png',
      status: PopupStatus.inProgress,
      latitude: 37.5443,
      longitude: 127.0560,
      isOperating: true,
    ),
    const Popup(
      id: 'travalo-perfume',
      title: '트라발로(Travalo) 휴대용 향수 팝업',
      category: '뷰티',
      area: '성수동',
      address: '서울 성동구 연무장길 3',
      subtitle: '글로벌 휴대용 향수 공병 브랜드 트라발로의 체험 팝업',
      period: '2026.06.06 - 2026.06.07',
      heroLabel: '오픈예정',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '11:00 - 18:30',
      distance: '280m away',
      dday: 'D-5',
      tags: ['PERFUME', 'BEAUTY', 'TRAVALO'],
      colors: [Color(0xFF1E293B), Color(0xFFF1F5F9)],
      imagePath: 'assets/images/search_result_interior.png',
      status: PopupStatus.openingSoon,
      latitude: 37.5442,
      longitude: 127.0525,
      isOperating: false,
    ),
    const Popup(
      id: 'niceghostclub-cowboy',
      title: '나이스고스트클럽 x 카우보이 비밥 팝업 @성수',
      category: '패션',
      area: '성수동',
      address: '서울 성동구 연무장길 15',
      subtitle: '카우보이 비밥 협업 콜라보 의류 및 전용 굿즈 팝업',
      period: '2026.05.26 - 2026.06.11',
      heroLabel: 'HOT',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '150m away',
      dday: 'D-10',
      tags: ['FASHION', 'ANIME', 'COLLAB'],
      colors: [Color(0xFF0F172A), Color(0xFF38BDF8)],
      imagePath: 'assets/images/calendar_xyz.png',
      status: PopupStatus.inProgress,
      latitude: 37.5431,
      longitude: 127.0550,
      isOperating: true,
    ),
    const Popup(
      id: 'seventeen-miniteen',
      title: '세븐틴 미니틴 팝업',
      category: '연예',
      area: '성수동',
      address: '서울 성동구 연무장15길 11',
      subtitle: 'Ice Cream with MINITEEN 테마 굿즈 숍 및 아이스 카페 팝업',
      period: '2026.05.23 - 2026.06.02',
      heroLabel: 'HOT',
      waitTime: '약 60분',
      entryFee: '무료',
      hours: '10:00 - 21:00',
      distance: '480m away',
      dday: '오늘 마감',
      tags: ['SEVENTEEN', 'KPOP', 'ICE_CREAM'],
      colors: [Color(0xFF3B0764), Color(0xFFF3E8FF)],
      imagePath: 'assets/images/home_trending_2.png',
      status: PopupStatus.inProgress,
      latitude: 37.5428,
      longitude: 127.0610,
      isOperating: true,
    ),
    const Popup(
      id: 'feev-musinsa',
      title: "FEEV x 무신사 'POP THAT BUBBLE'",
      category: '뷰티',
      area: '성수동',
      address: '서울 성동구 성수이로 18',
      subtitle: '피브의 수분 진정 뷰티 라인을 경험하는 팝업',
      period: '2026.05.06 - 2026.05.17',
      heroLabel: 'CLOSED',
      waitTime: '0분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '320m away',
      dday: '종료',
      tags: ['FEEV', 'BEAUTY', 'MUSINSA'],
      colors: [Color(0xFF1E3A8A), Color(0xFFDBEAFE)],
      imagePath: 'assets/images/detail_hero.png',
      status: PopupStatus.ended,
      latitude: 37.5455,
      longitude: 127.0595,
      isOperating: false,
    ),
    const Popup(
      id: 'toystory-house',
      title: '하우스 오브 토이 스토리 팝업',
      category: '캐릭터',
      area: '성수동',
      address: '서울 성동구 연무장길 9',
      subtitle: '1970-80년대 미국 빈티지 가정집 테마의 디즈니 토이 스토리 공간 팝업',
      period: '2026.05.23 - 2026.07.12',
      heroLabel: 'NEW',
      waitTime: '약 45분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '190m away',
      dday: 'D-41',
      tags: ['TOY_STORY', 'DISNEY', 'CHARACTER'],
      colors: [Color(0xFF78350F), Color(0xFFFEF3C7)],
      imagePath: 'assets/images/search_similar_1.png',
      status: PopupStatus.inProgress,
      latitude: 37.5446,
      longitude: 127.0538,
      isOperating: true,
    ),
    const Popup(
      id: 'musinsa-kicks',
      title: '무신사 킥스 서머 시즌 팝업 @성수',
      category: '패션',
      area: '성수동',
      address: '서울 성동구 성수이로 96',
      subtitle: '무신사가 선보이는 트렌디한 여름 스니커즈 셀렉션 팝업',
      period: '2026.05.28 - 2026.06.13',
      heroLabel: 'HOT',
      waitTime: '약 50분',
      entryFee: '무료',
      hours: '11:00 - 21:00',
      distance: '200m away',
      dday: 'D-12',
      tags: ['SNEAKERS', 'MUSINSA', 'SUMMER'],
      colors: [Color(0xFF9D174D), Color(0xFFFCE7F3)],
      imagePath: 'assets/images/search_similar_2.png',
      status: PopupStatus.inProgress,
      latitude: 37.5435,
      longitude: 127.0588,
      isOperating: true,
    ),
    const Popup(
      id: 'series-gto',
      title: '시리즈(series) x GTO RSG 성수 팝업',
      category: '애니',
      area: '성수동',
      address: '서울 성동구 연무장길 20',
      subtitle: '만화 GTO(반항하지마) 라이프스타일 굿즈 및 카페 콜라보 팝업',
      period: '2026.05.01 - 2026.05.10',
      heroLabel: 'CLOSED',
      waitTime: '0분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '310m away',
      dday: '종료',
      tags: ['ANIME', 'GTO', 'COLLAB'],
      colors: [Color(0xFF0369A1), Color(0xFFE0F2FE)],
      imagePath: 'assets/images/home_closing_1.png',
      status: PopupStatus.ended,
      latitude: 37.5425,
      longitude: 127.0585,
      isOperating: false,
    ),
    const Popup(
      id: 'metamong-playground',
      title: '메타몽 놀이터 팝업 (서울숲)',
      category: '캐릭터',
      area: '성수동',
      address: '서울 성동구 뚝섬로 273',
      subtitle: '서울숲 야외에 설치된 포켓몬 메타몽 테마 포토존 팝업',
      period: '2026.05.01 - 2026.06.21',
      heroLabel: 'NEW',
      waitTime: '약 60분',
      entryFee: '무료',
      hours: '11:00 - 21:00',
      distance: '170m away',
      dday: 'D-20',
      tags: ['POKEMON', 'METAMONG', 'PLAYGROUND'],
      colors: [Color(0xFF7F1D1D), Color(0xFFFCA5A5)],
      imagePath: 'assets/images/home_closing_2.png',
      status: PopupStatus.inProgress,
      latitude: 37.5412,
      longitude: 127.0550,
      isOperating: true,
    ),
    const Popup(
      id: 'monster-energy',
      title: '몬스터에너지 @이마트24 트렌드랩 성수 팝업',
      category: '음식',
      area: '성수동',
      address: '서울 성동구 성수이로 109',
      subtitle: '이마트24에서 열리는 몬스터에너지 시음 및 굿즈 교환 트렌드 팝업',
      period: '2026.05.25 - 2026.06.10',
      heroLabel: 'NEW',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '50m away',
      dday: 'D-9',
      tags: ['MONSTER', 'ENERGY', 'EMART24'],
      colors: [Color(0xFF1E293B), Color(0xFF86EFAC)],
      imagePath: 'assets/images/search_similar_1.png',
      status: PopupStatus.inProgress,
      latitude: 37.5447,
      longitude: 127.0563,
      isOperating: true,
    ),
    const Popup(
      id: 'cj-cultural',
      title: 'CJ문화재단 20주년 팝업스토어',
      category: '연예',
      area: '성수동',
      address: '서울 성동구 연무장길 17',
      subtitle: 'CJ문화재단 20주년 기념 인디음악 전시 및 스페셜 기프트 코너 팝업',
      period: '2026.06.01 - 2026.06.12',
      heroLabel: 'HOT',
      waitTime: '약 15분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '210m away',
      dday: 'D-11',
      tags: ['CJ', 'MUSIC', 'EXHIBIT'],
      colors: [Color(0xFF3B0764), Color(0xFFC084FC)],
      imagePath: 'assets/images/home_trending_2.png',
      status: PopupStatus.inProgress,
      latitude: 37.5436,
      longitude: 127.0515,
      isOperating: true,
    ),
    const Popup(
      id: 'coupang-beauty',
      title: '쿠팡 메가뷰티쇼 팝업',
      category: '뷰티',
      area: '성수동',
      address: '서울 성동구 연무장길 13',
      subtitle: '쿠팡 뷰티 어워즈 수상 브랜드 체험 및 사은품 증정 팝업 행사',
      period: '2026.05.28 - 2026.06.08',
      heroLabel: 'HOT',
      waitTime: '약 45분',
      entryFee: '무료',
      hours: '10:00 - 20:00',
      distance: '130m away',
      dday: 'D-7',
      tags: ['COUPANG', 'BEAUTY', 'AWARDS'],
      colors: [Color(0xFFDB2777), Color(0xFFFBCFE8)],
      imagePath: 'assets/images/calendar_beauty.png',
      status: PopupStatus.inProgress,
      latitude: 37.5445,
      longitude: 127.0550,
      isOperating: true,
    ),
    const Popup(
      id: 'collab-korea',
      title: '성수 콜랩코리아 팝업 스토어',
      category: '패션',
      area: '성수동',
      address: '서울 성동구 성수이로 98',
      subtitle: '다양한 인디 패션 브랜드들과 협업한 복합 팝업 스토어',
      period: '2026.05.20 - 2026.06.15',
      heroLabel: 'HOT',
      waitTime: '약 20분',
      entryFee: '무료',
      hours: '11:00 - 21:00',
      distance: '90m away',
      dday: 'D-14',
      tags: ['FASHION', 'COLLAB', 'BRAND'],
      colors: [Color(0xFF1E3A8A), Color(0xFF93C5FD)],
      imagePath: 'assets/images/home_trending_1.png',
      status: PopupStatus.inProgress,
      latitude: 37.5442,
      longitude: 127.0565,
      isOperating: true,
    ),
    const Popup(
      id: 'jeongfood-osse',
      title: '정식품 X 오쎄 이벤트 - 성수장터 팝업',
      category: '음식',
      area: '성수동',
      address: '서울 성동구 연무장1길 6',
      subtitle: '정식품 두유와 오쎄 뷰티의 컬래버레이션 이벤트 성수장터 팝업',
      period: '2026.05.29 - 2026.06.07',
      heroLabel: 'NEW',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '11:00 - 19:00',
      distance: '290m away',
      dday: 'D-6',
      tags: ['VEGEMIL', 'BEAUTY', 'FLEA_MARKET'],
      colors: [Color(0xFF0D9488), Color(0xFF99F6E4)],
      imagePath: 'assets/images/detail_nearby_restaurant.png',
      status: PopupStatus.inProgress,
      latitude: 37.5444,
      longitude: 127.0592,
      isOperating: true,
    ),
    const Popup(
      id: 'coucouette-rawum',
      title: '꾸꾸에떼 X 로엄 팝업',
      category: '패션',
      area: '성수동',
      address: '서울 성동구 연무장길 33',
      subtitle: '꾸꾸에떼와 로엄의 로맨틱 캐주얼 여름 의류 합작 팝업',
      period: '2026.06.01 - 2026.06.10',
      heroLabel: 'NEW',
      waitTime: '약 15분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '330m away',
      dday: 'D-9',
      tags: ['FASHION', 'ROMANTIC', 'SUMMER'],
      colors: [Color(0xFFE11D48), Color(0xFFFECDD3)],
      imagePath: 'assets/images/search_result_exterior.png',
      status: PopupStatus.inProgress,
      latitude: 37.5458,
      longitude: 127.0530,
      isOperating: true,
    ),
    const Popup(
      id: 'aerok-offbeauty',
      title: '에어로케이 X 오프뷰티 팝업',
      category: '뷰티',
      area: '성수동',
      address: '서울 성동구 연무장길 27',
      subtitle: '에어로케이 항공사와 오프뷰티의 여행용 뷰티 키트 기획전 팝업',
      period: '2026.06.05 - 2026.06.15',
      heroLabel: '오픈예정',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '12:00 - 20:00',
      distance: '410m away',
      dday: 'D-4',
      tags: ['AIRLINE', 'BEAUTY', 'TRAVEL'],
      colors: [Color(0xFF2563EB), Color(0xFFBFDBFE)],
      imagePath: 'assets/images/calendar_beauty.png',
      status: PopupStatus.openingSoon,
      latitude: 37.5450,
      longitude: 127.0505,
      isOperating: false,
    ),
    const Popup(
      id: 'censle-popup',
      title: '센슬 팝업스토어 : Busy, but still me',
      category: '리빙',
      area: '성수동',
      address: '서울 성동구 연무장길 11',
      subtitle: '바쁜 일상 속 나를 찾는 웰니스 향초 및 홈 프래그런스 기획 팝업',
      period: '2026.05.27 - 2026.06.08',
      heroLabel: 'NEW',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '11:00 - 19:30',
      distance: '220m away',
      dday: 'D-7',
      tags: ['CANDLE', 'WELLNESS', 'LIVING'],
      colors: [Color(0xFFD97706), Color(0xFFFEF3C7)],
      imagePath: 'assets/images/search_result_interior.png',
      status: PopupStatus.inProgress,
      latitude: 37.5433,
      longitude: 127.0535,
      isOperating: true,
    ),
    const Popup(
      id: 'magnesium-flea',
      title: '탄산 마그네슘 플리마켓 팝업',
      category: '리빙',
      area: '성수동',
      address: '서울 성동구 연무장길 12',
      subtitle: '스포츠 클라이밍 마니아들을 위한 탄산 마그네슘 파우더 플리마켓 팝업',
      period: '2026.05.30 - 2026.06.01',
      heroLabel: 'HOT',
      waitTime: '약 5분',
      entryFee: '무료',
      hours: '11:00 - 18:00',
      distance: '120m away',
      dday: '오늘 마감',
      tags: ['CLIMBING', 'FLEAMARKET', 'LIVING'],
      colors: [Color(0xFF4F46E5), Color(0xFFC7D2FE)],
      imagePath: 'assets/images/calendar_gallery.png',
      status: PopupStatus.inProgress,
      latitude: 37.5440,
      longitude: 127.0545,
      isOperating: true,
    ),
    const Popup(
      id: 'frica-seongsu',
      title: '프리카 성수 팝업',
      category: '패션',
      area: '성수동',
      address: '서울 성동구 성수이로 45',
      subtitle: '핸드메이드 주얼리 프리카의 성수 여름 특별 컬렉션 기획 쇼룸 팝업',
      period: '2026.05.15 - 2026.06.15',
      heroLabel: 'NEW',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '12:00 - 20:00',
      distance: '410m away',
      dday: 'D-14',
      tags: ['JEWELRY', 'HANDMADE', 'FASHION'],
      colors: [Color(0xFF0F172A), Color(0xFF94A3B8)],
      imagePath: 'assets/images/home_trending_2.png',
      status: PopupStatus.inProgress,
      latitude: 37.5412,
      longitude: 127.0605,
      isOperating: true,
    ),
    const Popup(
      id: 'tocobo-sun',
      title: '토코보 IN MY SUN ERA in 성수 팝업',
      category: '뷰티',
      area: '성수동',
      address: '서울 성동구 연무장길 20',
      subtitle: '비건 뷰티 토코보 선케어 라인업 실외 쿨링 바 체험 팝업스토어',
      period: '2026.05.22 - 2026.06.04',
      heroLabel: 'HOT',
      waitTime: '약 30분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '240m away',
      dday: 'D-3',
      tags: ['SUNSCREEN', 'VEGAN', 'BEAUTY'],
      colors: [Color(0xFFDB2777), Color(0xFFFCE7F3)],
      imagePath: 'assets/images/home_hero_popup.jpg',
      status: PopupStatus.inProgress,
      latitude: 37.5424,
      longitude: 127.0585,
      isOperating: true,
    ),
    const Popup(
      id: 'aespa-popup',
      title: 'aespa 팝업스토어',
      category: '연예',
      area: '성수동',
      address: '서울 성동구 아차산로 12',
      subtitle: '에스파 컴백 기념 전용 세계관 포토존 및 공식 한정 굿즈 판매 팝업스토어',
      period: '2026.05.27 - 2026.06.09',
      heroLabel: 'HOT',
      waitTime: '약 75분',
      entryFee: '무료',
      hours: '11:00 - 21:00',
      distance: '480m away',
      dday: 'D-8',
      tags: ['AESPA', 'KPOP', 'ALBUM'],
      colors: [Color(0xFF0F172A), Color(0xFFC084FC)],
      imagePath: 'assets/images/home_trending_1.png',
      status: PopupStatus.inProgress,
      latitude: 37.5465,
      longitude: 127.0520,
      isOperating: true,
    ),
    const Popup(
      id: 'mbn-orange',
      title: 'MBN 오렌지 스퀘어 팝업',
      category: '연예',
      area: '성수동',
      address: '서울 성동구 연무장길 19',
      subtitle: 'MBN 신규 프로그램 홍보 및 이벤트 포토 촬영 스튜디오 팝업',
      period: '2026.05.28 - 2026.06.10',
      heroLabel: 'NEW',
      waitTime: '약 20분',
      entryFee: '무료',
      hours: '12:00 - 20:00',
      distance: '100m away',
      dday: 'D-9',
      tags: ['MBN', 'BROADCAST', 'STUDIO'],
      colors: [Color(0xFFEA580C), Color(0xFFFED7AA)],
      imagePath: 'assets/images/calendar_xyz.png',
      status: PopupStatus.inProgress,
      latitude: 37.5451,
      longitude: 127.0545,
      isOperating: true,
    ),
    const Popup(
      id: 'roben-popup',
      title: '로벤 팝업스토어',
      category: '리빙',
      area: '성수동',
      address: '서울 성동구 연무장길 24',
      subtitle: '빈티지 레트로 가구 및 수제 목공 도마 특별 기획 팝업스토어',
      period: '2026.05.15 - 2026.05.31',
      heroLabel: 'CLOSED',
      waitTime: '0분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '290m away',
      dday: '종료',
      tags: ['ROBEN', 'FURNITURE', 'LIVING'],
      colors: [Color(0xFF78350F), Color(0xFFFEF3C7)],
      imagePath: 'assets/images/search_result_interior.png',
      status: PopupStatus.ended,
      latitude: 37.5438,
      longitude: 127.0602,
      isOperating: false,
    ),
    const Popup(
      id: 'rude-seongsu',
      title: '루드 Rude 팝업스토어',
      category: '패션',
      area: '성수동',
      address: '서울 성동구 성수이로26길 11',
      subtitle: '빈티지 캐주얼 브랜드 루드(Rude)의 팝업스토어',
      period: '2026.05.20 - 2026.06.15',
      heroLabel: 'NEW',
      waitTime: '약 10분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '310m away',
      dday: 'D-14',
      tags: ['RUDE', 'FASHION', 'VINTAGE'],
      colors: [Color(0xFFDC2626), Color(0xFFFEE2E2)],
      imagePath: 'assets/images/home_trending_1.png',
      status: PopupStatus.inProgress,
      latitude: 37.5440,
      longitude: 127.0490,
      isOperating: true,
    ),
    const Popup(
      id: 'likalika-sanrio',
      title: '리카리카 X 산리오캐릭터즈 성수 팝업',
      category: '캐릭터',
      area: '성수동',
      address: '서울 성동구 성수이로 94',
      subtitle: '반려동물 라이프스타일 브랜드 리카리카와 산리오캐릭터즈의 협업 팝업',
      period: '2026.05.25 - 2026.06.10',
      heroLabel: 'HOT',
      waitTime: '약 15분',
      entryFee: '무료',
      hours: '11:00 - 20:00',
      distance: '240m away',
      dday: 'D-9',
      tags: ['SANRIO', 'LIKALIKA', 'PET'],
      colors: [Color(0xFFEC4899), Color(0xFFFCE7F3)],
      imagePath: 'assets/images/calendar_gallery.png',
      status: PopupStatus.inProgress,
      latitude: 37.5435,
      longitude: 127.0561,
      isOperating: true,
    ),
    const Popup(
      id: 'yakult-seongsu',
      title: '야쿠르트 팝업스토어',
      category: '음식',
      area: '성수동',
      address: '서울 성동구 연무장길 20',
      subtitle: 'hy(한국야쿠르트) 팝업스토어 - 야쿠르트의 레트로 감성을 담은 디저트 카페',
      period: '2026.06.10 - 2026.06.20',
      heroLabel: '오픈예정',
      waitTime: '0분',
      entryFee: '무료',
      hours: '11:00 - 19:00',
      distance: '250m away',
      dday: 'D-9',
      tags: ['YAKULT', 'DESSERT', 'RETRO'],
      colors: [Color(0xFFEA580C), Color(0xFFFED7AA)],
      imagePath: 'assets/images/detail_nearby_restaurant.png',
      status: PopupStatus.openingSoon,
      latitude: 37.5448,
      longitude: 127.0570,
      isOperating: false,
    ),
  ];

  static final reviews = <PopupReview>[
    const PopupReview(
      author: '김민지',
      date: '2024.05.15',
      rating: 4.8,
      body: '공간이 너무 예뻐요. 평일에 방문해서 웨이팅 없이 잘 구경했습니다.',
    ),
    const PopupReview(
      author: 'Park Jun',
      date: '2024.05.12',
      rating: 4.6,
      body: '입구 정원이 포토존이에요. 주말에는 미리 예약하고 오시는 걸 추천합니다.',
    ),
    const PopupReview(
      author: '이영희',
      date: '2024.05.10',
      rating: 4.9,
      body: '성수동 오면 꼭 들러야 할 팝업. 굿즈들도 다양해서 좋았어요.',
    ),
  ];

  static final inventory = <InventoryProduct>[
    const InventoryProduct(
      name: '한정판 세라믹 머그',
      category: 'Living / Ivory Matte',
      price: '₩32,000',
      status: '여유',
    ),
    const InventoryProduct(
      name: '아로마 디퓨저 세트',
      category: 'Beauty / Cloud',
      price: '₩48,000',
      status: '품절 임박',
    ),
    const InventoryProduct(
      name: '시그니처 토트백',
      category: 'Fashion / Black',
      price: '₩39,000',
      status: '품절',
    ),
  ];

  static final calendarEvents = <CalendarEvent>[
    const CalendarEvent(
      day: 1,
      title: '성수 XYZ 팝업',
      area: '성수동',
      period: '2024.12.01 - 2024.12.15',
      status: '운영 중',
    ),
    const CalendarEvent(
      day: 13,
      title: '한남 모던 갤러리 팝업',
      area: '한남동',
      period: '2024.11.25 - 2024.12.13',
      status: 'D-2 종료 임박',
    ),
    const CalendarEvent(
      day: 25,
      title: '청담 시그니처 뷰티',
      area: '청담동',
      period: '2024.12.05 - 2024.12.25',
      status: '예약중',
    ),
  ];
}
