final List<Map<String, dynamic>> communitySeedPosts = [
  {
    'author': '김민지',
    'authorId': 'mock_1',
    'category': '메이트',
    'title': '탬버린즈 성수 워크숍 같이 가실 분!',
    'popupTitle': 'Tamburins Seongsu',
    'body': '이번 주말 성수동 팝업 같이 돌면서 사진 찍고 이야기하실 분 찾아요.',
    'likes': 12,
    'comments': 2,
    'status': '2/4 모집중',
    'area': '성수',
    'likedBy': <String>[],
    'createdAt': DateTime.now().subtract(const Duration(hours: 1)),
  },
  {
    'author': '박알렉스',
    'authorId': 'mock_2',
    'category': '후기',
    'title': 'Dior Concept Store는 오전 방문 추천',
    'popupTitle': 'Dior Concept Store',
    'body': '전시가 정말 아름다웠어요. 오전 일찍 방문하시는 것을 강력 추천합니다.',
    'likes': 45,
    'comments': 5,
    'status': 'HOT',
    'area': '성수',
    'likedBy': <String>[],
    'createdAt': DateTime.now().subtract(const Duration(hours: 5)),
  },
];
